[workspace]
resolver = "2"
members = [
    "crates/mira-cpu",
    "crates/mira-asm",
    "crates/mira-emu",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
mira-cpu = { path = "crates/mira-cpu" }
mira-asm = { path = "crates/mira-asm" }
